apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-aws-elasticache
  annotations:
    meta.crossplane.io/maintainer: The configuration-aws-elasticache Configuration
    meta.crossplane.io/source: github.com/upbound/configuration-aws-elasticache
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      This configuration-aws-elasticache configuration offers
      Cluster, ParameterGroup, ReplicationGroup, SubnetGroup,
      UserGroup, and User provisioning for AWS Elasticache.
    meta.crossplane.io/readme: |
      This Configuration bundles an Upbound Cloud
      extension and an API definition. The API will
      allow control planes to provision AWS Elasticache
      using the provider-aws-elasticache from the Upbound
      marketplace.
spec:
  crossplane:
    version: ">=v1.15.0-0"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-aws-elasticache
      version: "v1.3.1"
    - function: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform
      version: "v0.4.0"
    - configuration: xpkg.upbound.io/upbound/configuration-aws-network
      version: "v0.13.0"
