---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xparametergroups.elasticache.aws.platform.upbound.io
spec:
  group: elasticache.aws.platform.upbound.io
  names:
    kind: XParameterGroup
    plural: xparametergroups
  claimNames:
    kind: ParameterGroup
    plural: parametergroups
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  description: >-
                    Elasticache Parameter Group Parameters
                  properties:
                    deletionPolicy:
                      description: >-
                        Defaults to Delete
                      enum:
                        - Delete
                        - Orphan
                      type: string
                      default: Delete
                    family:
                      description: >-
                        The family of the ElastiCache parameter group.
                      type: string
                    name:
                      description: >-
                        The ElastiCache parameter group external name.
                      type: string
                    parameter:
                      description: >-
                        A list of ElastiCache parameters to apply.
                      items:
                        properties:
                          name:
                            description: >-
                              The name of the ElastiCache parameter group.
                            type: string
                          value:
                            description: >-
                              The value of the ElastiCache parameter.
                            type: string
                        required:
                          - name
                          - value
                        type: object
                      type: array
                    region:
                      type: string
                    tags:
                      additionalProperties:
                        type: string
                      description: >-
                        Key-value map of resource tags.
                      type: object
                    tagsAll:
                      additionalProperties:
                        type: string
                      description: >-
                        A map of tags assigned to the resource,
                        including those inherited from the provider
                        default_tags configuration block.
                      type: object
                    providerConfigName:
                      description: >-
                        Crossplane ProviderConfig to use for
                        provisioning the resources.
                      type: string
                      default: default
                  required:
                    - deletionPolicy
                    - name
                    - providerConfigName
                    - region
                  type: object
              required:
                - parameters
            status:
              properties:
                elasticacheParameterGroup:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
